name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      
      - name: Install dependencies (Rust)
        run: |
          rustup target add aarch64-apple-darwin
      
      - name: Install dependencies (macOS)
        run: |
          brew install cmake
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build Tauri App
        run: bun run tauri build --target 'aarch64-apple-darwin'
      
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error 